### ISSUE TITLE
Не показывать тип документа во вложениях, если в сообщении нет текста

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#111]
И если вложение только одно

**Comment by BANOnotIT** [comment]
Можно вопрос, а зачем это нужно?

**Comment by mrDoctorWho** [comment]
Затем, чтобы клиенты вроде Conversations показывали вложения, а не ссылки

**Comment by mrDoctorWho** [comment]
Похоже, более не актуально.
