### ISSUE TITLE
Транспорт путает тип сообщения

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#113]
Присылает сообщения из групчатов как личные.

**Comment by ildar** [comment]
У меня иногда чат теряет всех членов. Возвращаются, когда кто-нибудь другой
пишет в чат.
Возможно, тут есть связь?

**Comment by mrDoctorWho** [comment]
Связи нет, но нужны подробности. Когда теряет?

**Comment by mrDoctorWho** [comment]
После перехода на API v3.0 в d5d26b2ec22bb6a4f1aba32c48479c8798127da4 такой проблемы больше быть не должно.
