### ISSUE TITLE
Miranda-based клиенты неправильно определяют транспорт

### ISSUE THREAD

**Issue by mrDoctorWho** [mrDoctorWho/vk4xmpp#138]
Из-за замены gc-1.0 на jabber.org/protocol/muc miranda-based клиенты принимают транспорт за сервер конференций.

**Comment by mrDoctorWho** [comment]
8f370bfda4ba731ae3a76a4ce04a03882167cb7a

**Comment by yagiza** [comment]
И как это проявляется?

**Comment by mrDoctorWho** [comment]
Они хотят в него зайти, будто он конференция и не дают зарегистрироваться

**Comment by yagiza** [comment]
Вот ради того, чтобы такие дебильные клиенты отсекать, и нужно делать всё по стандарту!

**Comment by mrDoctorWho** [comment]
Мне, как разработчику, интересна поддержка большего количества клиентов. За
исключением случаев, которые я считаю абсурдными и которые не мешают
пользоваться транспортом.

**Comment by yagiza** [comment]
Такой подход имеет право на существование. Но к сожалению, он приводит к тому, что мы имеем: ни одного нормального XMPP-клиента: все как один имеют какие-то глюки и несовместимости.

**Comment by mrDoctorWho** [comment]
@yagiza Как по-твоему клиент должен определять, чем является определенная нода на сервере? Он видит jabber.org/protocol/muc и решает, что это MUC. Вроде бы всё логично, нет?

**Comment by yagiza** [comment]
Нет. Тип сущности определяется по элементам <identity/>, а не по элементам <feature/> в disco#info.
Согласно [XEP-0045](http://xmpp.org/extensions/xep-0045.html#registrar-discocat), сервер конференций должен определяться по категории "conference" и по типу "text".
Элементы <feature/> нужны для того, чтобы определять, с какими фичами умеет работать данная сущность, а не для определения её типа. Все (нормальные) клиенты, поддерживающие работу с MUC тоже, публикуют эту фичу в disco#info, так что, миранда все контакты, сидящие на таких клиентах тоже, серверами конференций считает?

**Comment by mrDoctorWho** [comment]
> Все (нормальные) клиенты, поддерживающие работу с MUC тоже, публикуют эту фичу в disco#info, так что, миранда все контакты, сидящие на таких клиентах тоже, серверами конференций считает?

Насколько мне известно, это происходит только в обзоре сервисов.

**Comment by yagiza** [comment]
> Насколько мне известно, это происходит только в обзоре сервисов.
Ну а кто мешает в обзоре сервисов вбить полный жид контакта?

**Comment by mrDoctorWho** [comment]
Пользователь скорее решит, что транспорт ему не нужен и уйдет, чем будет пытаться заставить его работать.

**Comment by yagiza** [comment]
Вполне возможно. Другое дело, нужны ли тебе пользователи, сидящие в таких клиентах? Обычно с такими пользователями один геморрой.
