### ISSUE TITLE
XEP-0280: Message Carbons

### ISSUE THREAD

**Issue by korobcov** [mrDoctorWho/vk4xmpp#144]
запилить сабж

**Comment by mrDoctorWho** [comment]
Пока засуну в milestone 3.5, потом может уберу

**Comment by korobcov** [comment]
пояснения:
синхронизировать отправленные через web сообщения с подключенными клиентами

**Comment by mrDoctorWho** [comment]
Нельзя carbons от транспорта. В стандарте этого нет, а если пытаться отправлять, то работает совсем не так, как хотелось бы
