### ISSUE TITLE
Транспорт шлёт теперь все сообщения из чята в личку

### ISSUE THREAD

**Issue by l29ah** [mrDoctorWho/vk4xmpp#145]
b52b9d23e2c7ff33ac89022a374e9022dc5ddab8 is the first bad commit

**Comment by mrDoctorWho** [comment]
На самом деле проблема пришла из d77546bb403578bf4b4af722775c3eb9e40b1ecf, после этого коммита перестали приходить инвайты. Потом я починил инвайты, но при этом совсем сломал групчаты. Лог ошибки был бы кстати, он почти наверняка есть.
