### ISSUE TITLE
KeyError on USERS_ON_INIT[source].add(vk2xmpp(destination))

### ISSUE THREAD

**Issue by korobcov** [mrDoctorWho/vk4xmpp#150]
| 26.12.2016 (06:38:46) |
```python
Traceback (most recent call last):
  File "./gateway.py", line 1105, in loop
    Component.iter(6)
  File "library/xmpp/dispatcher.py", line 176, in Process
    deferredRaise(self._pendingExceptions.pop())
  File "library/xmpp/dispatcher.py", line 403, in dispatch
    handler["func"](session, stanza)
  File "modules/mod_prs_main.py", line 132, in presence_handler
    USERS_ON_INIT[source].add(vk2xmpp(destination))
KeyError: u'hacker@baron.pro'
```

**Comment by mrDoctorWho** [comment]
Проблема вызвана коммитом a5354a9f365dd3e18f10314d25dd36609671d640.

Перепишу на БД.

**Comment by opiums9** [comment]
Обновил транспорт, заметил у себя точно такую же ошибку в краш-логах, проблема уже решена? Если да - то так мне избавиться от данной ошибки?
P.S. При обновлении оставил старыми файлы конфига, пида и .db, чтобы не авторизовываться 2й раз в транспорте.

**Comment by mrDoctorWho** [comment]
@opiums9 если бы проблема была решена, то issue было бы закрыто.

У меня пока не доходят руки до починки. Нужно хранить друзей в базе, а для этого придётся переписать схему бд.

Чтобы ничего не сломать, надо либо скрипт обновления добавить, либо придумать что-то ещё. Поэтому я не особо тороплюсь с реализацией.

Проблема не должна быть критичной. В худшем случае плагины, зарегистрированные на презенсы не отработают.

**Comment by mrDoctorWho** [comment]
@opiums9 не стоит редактировать комментарии. Я не получаю оповещений об измененных комментариях.

О main.disconnect я не подумал. Откачу коммит.

**Comment by mrDoctorWho** [comment]
Revert "Make roster check xmpp-based" c60c434bfaf6e39739eec88193ee875441c9acc6

**Comment by mrDoctorWho** [comment]
@opiums9 @korobcov нужно обновиться

**Comment by opiums9** [comment]
@mrDoctorWho хорошо, я просто решил дополнить сообщение, буду знать. 
Обновился, обо всех ошибках - отпишусь, если они будут.

**Comment by opiums9** [comment]
Отписываюсь... 
**1. ****Самое основное** - почему такие _дикие_ лаги? Сообщения приходят с задержкой порой в **пол минуты**, как это исправить? Лаги не зависимо от времени суток.
**2.** Если меня пригласили в чат, в транспорт ничего не приходит... Конференция есть, в вк сообщения есть, а в клиенте ничего. Принудительно подключился к конференции.
Кусок лога:
`13.01.2017 15:13:15 DEBUG:vk4xmpp: groupchats: creating 21839934_chat#37@conference.opiums.eu. Users: [u'26319709', u'47749541']; owner: 26319709 (jid: dima@opiums.eu)
13.01.2017 15:13:15 DEBUG:vk4xmpp: groupchats: groupchat 21839934_chat#37@conference.opiums.eu will be added to the database (jid: dima@opiums.eu)
13.01.2017 15:13:15 DEBUG:vk4xmpp: groupchats: presence error (error #None, status #110) from source 21839934_chat#37@conference.opiums.eu (jid: dima@opiums.eu)
13.01.2017 15:13:15 DEBUG:vk4xmpp: Got a presence. Searching jid in the database. (jid: 21839934_chat#37@conference.opiums.eu)
13.01.2017 15:13:15 DEBUG:vk4xmpp: User initialized (jid: 21839934_chat#37@conference.opiums.eu)
13.01.2017 15:13:15 DEBUG:vk4xmpp: User connecting (jid: 21839934_chat#37@conference.opiums.eu)
13.01.2017 15:13:15 WARNING:vk4xmpp: User wasn't found in the database and no token or password was given!
13.01.2017 15:13:16 DEBUG:vk4xmpp: groupchats: stanza "result" received from 21839934_chat#37@conference.opiums.eu, continuing initialization (jid: dima@opiums.eu)
13.01.2017 15:13:16 DEBUG:vk4xmpp: groupchats: user has been invited to chat 21839934_chat#37@conference.opiums.eu (jid: dima@opiums.eu)
13.01.2017 15:13:16 DEBUG:vk4xmpp: groupchats: presence error (error #None, status #110) from source 21839934_chat#37@conference.opiums.eu (jid: dima@opiums.eu)
13.01.2017 15:13:16 DEBUG:vk4xmpp: Got a presence. Searching jid in the database. (jid: 21839934_chat#37@conference.opiums.eu)
13.01.2017 15:13:16 DEBUG:vk4xmpp: User initialized (jid: 21839934_chat#37@conference.opiums.eu)
13.01.2017 15:13:16 DEBUG:vk4xmpp: User connecting (jid: 21839934_chat#37@conference.opiums.eu)
13.01.2017 15:13:16 WARNING:vk4xmpp: User wasn't found in the database and no token or password was given!
13.01.2017 15:13:17 DEBUG:vk4xmpp: groupchats: user 26319709 has joined the chat 21839934_chat#37@conference.opiums.eu (jid: dima@opiums.eu)
13.01.2017 15:13:17 DEBUG:vk4xmpp: groupchats: user 47749541 has joined the chat 21839934_chat#37@conference.opiums.eu (jid: dima@opiums.eu)
13.01.2017 15:13:17 DEBUG:vk4xmpp: Got a presence. Searching jid in the database. (jid: 21839934_chat#37@conference.opiums.eu)`
Возможно проблема в моём конфиге... Прошу помочь мне с этим.
**3. register_handler** crash:
```
| 13.01.2017 (15:25:18) |
Traceback (most recent call last):
  File "library\utils.py", line 70, in wrapper
    func(*args)
  File "modules\mod_iq_register.py", line 80, in register_handler
    user = Transport[source]
TypeError: 'Transport' object has no attribute '__getitem__'
```

**Comment by mrDoctorWho** [comment]
@opiums9 с такими вещами лучше в конференцию обращаться. И текущий issue не имеет отношения к твоей проблеме.

1. По поводу лагов ничего не могу сказать. Откатись назад и посмотри, есть ли разница. 
2. В логе есть сообщение об инвайте. Смотри со своей стороны. Если я не ошибаюсь, у тебя Openfire, может быть они что-то изменили, что теперь транспортам нельзя рассылать инвайты?
```
13.01.2017 15:13:16 DEBUG:vk4xmpp: groupchats: user has been invited to chat 21839934_chat#37@conference.opiums.eu (jid: dima@opiums.eu)
```
3. Исправил в fcb794ec6f325a40c8e39d1cd1da71a46b9bd7c3.

**Comment by opiums9** [comment]
@mrDoctorWho на старой версии до обновления задержка была очень редко, я её практически не замечал, то была **версия от 26.01.2016**, откатился - лагов нет... На новой версии сразу же откуда то появляется непонятная задержка 10-30 секунд... Но иногда её нет.
Да, openfire, я даже не знаю пока куда копать, попробую поискать в конфиге инвайты.
За исправление большое спасибо!

**Comment by mrDoctorWho** [comment]
@opiums9 предлагаю пройти в simpleapps@conference.helldev.net для дальнейшего обсуждения проблемы.

**Comment by mrDoctorWho** [comment]
@opiums9 я так понимаю, больше не актуально?

**Comment by opiums9** [comment]
@mrDoctorWho очень сложно разобраться в таких вещах, когда плохо разбираешься в программировании и git у меня не получился

**Comment by mrDoctorWho** [comment]
@opiums9 надо было тогда снова прийти и мы бы попробовали решить проблему иначе.

**Comment by opiums9** [comment]
@mrDoctorWho ну хорошо, сейчас загляну

**Comment by mrDoctorWho** [comment]
Проблема, указанная в первом комментарии более не проявляется.
