### ISSUE TITLE
Не приходит первое сообщение в конференции от другого пользователя

### ISSUE THREAD

**Issue by eg-astrouka** [mrDoctorWho/vk4xmpp#160]
Периодически пропадает первое сообщение. В последний раз было замечено 19.01.2017 в 22:00 (Мск) в чате #17. 
Вот что я вижу в конференции:
[22:00]	Тема 'ХХХ' (установлена @vk.jabberik.ru)
[22:00]	@vk.jabberik.ru (vk.jabberik.ru) сменил имя на имя_создателя.
[22:00]	"второе сообщение"

**Comment by mrDoctorWho** [comment]
Лог транспорта на этот момент:

19.01.2017 19:00:12 DEBUG:vk4xmpp: groupchats: creating userid_chat#17@conference.jabbik.ru. Users: [u'1', u'2']; owner: 2 (jid: user_jid)
19.01.2017 19:00:12 DEBUG:vk4xmpp: groupchats: groupchat userid_chat#17@conference.jabbik.ru exists in the database (jid: user_jid)
19.01.2017 19:00:13 DEBUG:vk4xmpp: groupchats: chat userid_chat#17@conference.jabbik.ru wasn't created well, so trying to create it again (jid: user_jid)
19.01.2017 19:00:13 DEBUG:vk4xmpp: groupchats: chat userid_chat#17@conference.jabbik.ru wasn't created well, so trying to create it again (jid: user_jid)
19.01.2017 19:00:20 DEBUG:vk4xmpp: groupchats: stanza "result" received from userid_chat#17@conference.jabbik.ru,continuing initialization (jid: user_jid)
19.01.2017 19:00:20 DEBUG:vk4xmpp: groupchats: user has been invited to chat userid_chat#17@conference.jabbik.ru (jid: user_jid)
19.01.2017 19:00:20 DEBUG:vk4xmpp: groupchats: presence error (error #409, status #None)from source userid_chat#17@conference.jabbik.ru (jid: user_jid)
19.01.2017 19:00:21 DEBUG:vk4xmpp: groupchats: presence error (error #None, status #110)from source userid_chat#17@conference.jabbik.ru (jid: user_jid)
19.01.2017 19:00:21 DEBUG:vk4xmpp: groupchats: presence error (error #None, status #110)from source userid_chat#17@conference.jabbik.ru (jid: user_jid)
19.01.2017 19:00:29 DEBUG:vk4xmpp: groupchats: user 1 has joined the chat userid_chat#17@conference.jabbik.ru (jid: user_jid)
19.01.2017 19:00:29 DEBUG:vk4xmpp: groupchats: user 2 has joined the chat userid_chat#17@conference.jabbik.ru (jid: user_jid)
19.01.2017 19:00:29 DEBUG:vk4xmpp: groupchats: presence error (error #None, status #110)from source userid_chat#17@conference.jabbik.ru (jid: user_jid)
19.01.2017 19:00:29 DEBUG:vk4xmpp: groupchats: presence error (error #None, status #110)from source userid_chat#17@conference.jabbik.ru (jid: user_jid)

**Comment by mrDoctorWho** [comment]
Решение мне видится таким: если не удалось создать чат, то мы по-прежнему пытаемся его пересоздать, но при этом уже принятое сообщение будет отправлено в какой-нибудь буфер, из которого оно вытащится первым делом при удачной инициализации.

Плюс ко всему, мне кажется, следует добавить ожидание презенса из чата (т.е. определять удачное создание/вхождение).

**Comment by mrDoctorWho** [comment]
Ждём новых групчатов.
