### ISSUE TITLE
XEP-0333: Chat Markers

### ISSUE THREAD

**Issue by ghost** [mrDoctorWho/vk4xmpp#176]
Неплохо было бы реализовать [XEP-0333: Chat Markers](https://xmpp.org/extensions/xep-0184.html), чтобы транспорт мог определять, что пользователь прочитал сообщения и сообщать об этом VK и наоборот, сообщать пользователю о том, что его сообщения прочитаны.

**Comment by BANOnotIT** [comment]
Тогда неплохо было бы реализовать ещё и отключение этого замечательного функционала)

**Comment by mrDoctorWho** [comment]
@BANOnotIT 

Это несложно, сложнее написать Chat Markers. Хотя, не знаю, как оно будет в 4.0.

**Comment by mrDoctorWho** [comment]
Сделано в d35622d82961a43fd83a80c60ce6527e1dfb95a9.
