### ISSUE TITLE
Не отправляются сообщения в групчатах

### ISSUE THREAD

**Issue by lexghjc** [mrDoctorWho/vk4xmpp#177]
1. зайти в чат с клиента1
2. зайти туда же с другим ником с клиента2 (жид тот же)
3. выйти клиентом2
4. написать мессагу клиентом1
PROFIT: мессаги нет.

**Comment by mrDoctorWho** [comment]
С новыми групчатами (которых пока нет) становится неактуальным.

Оставлять и поддерживать старые не имеет смысла.
