### ISSUE TITLE
TokenError is undefined in modules/mod_prs_main.py

### ISSUE THREAD

**Issue by lierdakil** [mrDoctorWho/vk4xmpp#178]
But it is used in https://github.com/mrDoctorWho/vk4xmpp/blob/master/modules/mod_prs_main.py#L26

Stumbled upon this while tracing down another unrelated issue.

Quick fix:

Add
```python
from vkapi import TokenError
```
to `mod_prs_main.py`

**Comment by mrDoctorWho** [comment]
Hello,

Thank you for your report. Actually, modules should already have api or vkapi module in their globals(), so it would be better to use it.

I must say that it's not currently possible (well, it is, but there is no point of doing that)  to fix that error. 
I started a huge refactoring, with brand new project structure, which will have no place for the __main__ imports.

I don't know how long it's gonna take, so if it'll take longer than I expected, I'll fix this.

**Comment by lierdakil** [comment]
Up to you. It's not like this is a huge issue. Although `sendMessage` is never executed due to this, so users have no indication of authentication failure.

**Comment by mrDoctorWho** [comment]
Fixed.
