### ISSUE TITLE
longpoll внезапно сломан

### ISSUE THREAD

**Issue by lierdakil** [mrDoctorWho/vk4xmpp#179]
Первый "плохой" коммит 9c5e7f1aa6022fe2a36804dd68ea6ac1c70c960e судя по всему. На последней версии плюется несколько раз в секунду сообщениями типа `ERROR:vk4xmpp: longpoll: failed to make poll`. 621a8a6 при этом работает как ожидается: `longpoll: successfully initialized longpoll`

**Comment by mrDoctorWho** [comment]
longpoll неоднократно чинился, последняя ревизия точно не работает?

**Comment by lierdakil** [comment]
Ветка `testing`: 043330d
Засыпает сообщениями вида ` DEBUG:vk4xmpp: longpoll: failed. Searching for a new server`

Ветка `master`: f6bf2b5
```
...
DEBUG:vk4xmpp: longpoll: adding user to the init buffer 
DEBUG:vk4xmpp: longpoll: requesting server address 
DEBUG:vk4xmpp: longpoll: server: https://newimv4.vk.com/nim2568 
DEBUG:vk4xmpp: longpoll: successfully initialized longpoll 
DEBUG:vk4xmpp: longpoll: failed. Searching for a new server 
ERROR:vk4xmpp: longpoll: failed to make poll 
DEBUG:vk4xmpp: longpoll: adding user to the init buffer 
DEBUG:vk4xmpp: longpoll: requesting server address 
...
```

Вроде f6bf2b5 последняя?

Я вот правда задумался, а действительно ли 621a8a6 работает, или просто об ошибках не сообщает? Выясню -- доложу...

**Comment by mrDoctorWho** [comment]
Testing устарел. На master в логах вижу Internal Server Error от ВК за вчерашний день и не на одном транспорте. Картина в приведенных выше логах выглядит действительно странно, но вроде по коду всё чисто.

За вчерашний день в логах вижу кучу InternalServerError, проблема была обнаружена вчера?

```
3.03.2017 13:42:17 ERROR:vk4xmpp: vkapi: error occured on executing method (messages.getLongPollServer({'access_token': ', 'use_ssl': 1, 'need_pts': 0, 'v': '3.0'}), code: 10, msg: Internal server error), (for: @jabberik.ru)
13.03.2017 13:42:17 ERROR:vk4xmpp: VK: error InternalServerError occurred while executing method(messages.getLongPollServer) (Internal server error) (jid: @jabberik.ru)
13.03.2017 13:42:27 DEBUG:vk4xmpp: longpoll: requesting server address (jid: @jabberik.ru)
13.03.2017 13:42:41 ERROR:vk4xmpp: vkapi: error occured on executing method (messages.getLongPollServer({'access_token': ', 'use_ssl': 1, 'need_pts': 0, 'v': '3.0'}), code: 10, msg: Internal server error), (for: @jabberik.ru)
13.03.2017 13:42:41 ERROR:vk4xmpp: VK: error InternalServerError occurred while executing method(messages.getLongPollServer) (Internal server error) (jid: @jabberik.ru)
```

**Comment by lierdakil** [comment]
Увы нет, не вчера. Лог я неосмотрительно потер уже, так что точно не скажу,
но где-то 4-5 марта по всей вероятности. Просто руки не доходили этим
заняться... Есть вероятность, что проблема на стороне вконтакта. Но плохо
представляю как это проверить наверняка.

вт, 14 мар. 2017 г., 12:51 John Smith <notifications@github.com>:

**Comment by lierdakil** [comment]
И кстати судя по логам пакетов messages.getLongPollServer отрабатывает
штатно и проблема возникает только на сервере лонгполла (newimv4 или как
его там). Сходу не скажу что он отвечает, посмотрю вечером.

вт, 14 мар. 2017 г., 13:12 Nikolay Yakimov <root@livid.pp.ru>:

**Comment by lierdakil** [comment]
Так, разобрался. TL;DR проблема на моем конце.

Вконтакт для хэша ключа использует помимо прочего ip, с которого сделан запрос. А у меня multihoming на сервере, причем по хэшу целевого ip. Принудительное использование стабильного выходного адреса для гейта решило проблему. Прошу прощения за беспокойство.

**Comment by mrDoctorWho** [comment]
> Вконтакт для хэша ключа использует помимо прочего ip, с которого сделан запрос.

Это для какого? Для access-token что ли?

**Comment by lierdakil** [comment]
> Это для какого? Для access-token что ли?

Для того, который передается на сервер longpoll в поле key. Который берется из `messages.getLongPollServer`.

**Comment by mrDoctorWho** [comment]
А, точно. Я что-то забыл про него.

longpoll что-то очень плохо в последнее время работает, но пока не пойму почему. Поэтому пускай задача пока открытой повисит.

**Comment by mrDoctorWho** [comment]
Вроде бы всё стабильно. Можно закрывать.

Если будут проблемы, можно свободно переоткрывать.
