### ISSUE TITLE
описание

### ISSUE THREAD

**Issue by steamlinux** [mrDoctorWho/vk4xmpp#203]
ссылка на обсуждение форума в дебиане немного неправильная, слеш не там (https://debianforum.r/uindex.php?topic=6037)
собственно нет инструкции по установке на сервере дебиана
P.S. я не дотошный)

**Comment by mrDoctorWho** [comment]
> нет инструкции

Как это нет? А [это](https://github.com/mrDoctorWho/vk4xmpp/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-\(%D0%B4%D0%BB%D1%8F-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BE%D0%B2\)) что?

**Comment by mrDoctorWho** [comment]
А вот в README ссылка неправильная, да.

**Comment by mrDoctorWho** [comment]
5cf3767afba260b840e3ea34c0d86ef6d6388e6f

**Comment by steamlinux** [comment]
до этого момента по ссылке на инструкцию мне выдавало пустую страницу с предложением создать ее

**Comment by mrDoctorWho** [comment]
@steamlinux, да, я поправил README.
