### ISSUE TITLE
Транспорт повторно отправляет сообщения

### ISSUE THREAD

**Issue by Ledarium** [mrDoctorWho/vk4xmpp#227]
При получении сообщения в конференции, происходит следующее:

>мое сообщение 1
>мое сообщение 2
>мое сообщение 3
< входящее сообщение
>мое сообщение 1
>мое сообщение 2
>мое сообщение 3

При большом количестве отправляемых сообщений останавливается только после получения капчи. В DEBUG логах ничего подозрительного нет, просто сразу после getMessagesBulk выполняется messages.getChat и отправляется куча messages.send для предыдущих сообщений. Возможно связано с #223 . 
Сервер ejabberd 18.01
[почищенный log.txt](https://github.com/mrDoctorWho/vk4xmpp/files/3156887/log.txt)

**Comment by mrDoctorWho** [comment]
Нужны нормальные логи. Отдельно XMPP и отдельно vk4xmpp.log.

Ещё мне не совсем ясна суть проблемы. С какой стороны повторная отправка происходит? Транспорт отправляет повторно в XMPP или во ВК?

**Comment by mrDoctorWho** [comment]
Закрываю из-за неактивности.
