### ISSUE TITLE
Ошибка регистрации

### ISSUE THREAD

**Issue by AlexanderPanshin** [mrDoctorWho/vk4xmpp#239]
Здравствуйте. Неожиданно перестал работать транспорт "Ошибка токена. переустановка транспорта не помогла регистрация не проходит так как неверный токен. Что может быть что посмотреть ?

**Comment by mrDoctorWho** [comment]
Здравствуйте! Попробуйте обновиться на новую версию и пройти регистрацию заново. ВКонтакте поменяли формат токенов, поэтому регистрация работала неправильно, а старые токены потеряли актуальность.

https://github.com/mrDoctorWho/vk4xmpp/commit/542abe296ea78d513df75bac80158c8c024d6f72

**Comment by AlexanderPanshin** [comment]
Благодарю, за оперативную работу все функционирует
