### ISSUE TITLE
Несовпадение капчи

### ISSUE THREAD

**Issue by ktulx** [mrDoctorWho/vk4xmpp#5]
Добрый день.
Изредка приходит запрос подтверждения капчи, раз пятьдесят пробовал - бесполезно.

"WARNING: VK sent captcha to you.Please, go to http://api.vk.com/captcha.php?sid=ХХХХХХХХХХХХ and enter text from image to chat.Example: !captcha my_captcha_key. Tnx 
Captcha invalid."

Ввожу так: !captcha код-с-картинки.
Для чего это вообще нужно? Чем грозит не-ввод капчи?

Спасибо.

**Comment by ildar** [comment]
Надо в сообщении о капче предупреждать, чтобы не пользовались Firefox.

**Comment by Atterratio** [comment]
Странно, я юзаю FF капча давно не вылезала, но когда вылезала всё было норм.

**Comment by mrDoctorWho** [comment]
@Atterratio, речь о прохождении капчи с Firefox. Транспорт присылает ссылку на капчу, пользователь открывает её в Firefox, смотрит, отправляет текст с картинки транспорту — а он её не принимает. С Chrome/Chromium такого поведения не замечено.

Я не разбирался, почему так происходит. На момент создания этого issue, я считал, что это проявляется в любых браузерах. А когда узнал, что это касается только Firefox, что-то решать было уже поздно: транспорт прошёл свой пик активности и если создать очередной багрепорт в трекере VK, на него уже не подпишется достаточное количество человек, чтобы его заметили.

@ildar, следовало создать отдельную задачу для этого.

**Comment by ildar** [comment]
Я подумал, что это - та же самая проблема. Поэтому решил не открывать новую.
По сути проблемы: возможно, ВК предлагает разные капчи для фф и для других.
Транспорт запрашивает одно, Капча другая (фф user agent), транспорт отдаёт
Капчу снова от себя (не фф user agent). В этом несовпадении, возможно, и
кроется причина.

**Comment by mrDoctorWho** [comment]
@ildar, транспорт работает с API и там, кстати, User-Agent Firefox под Ubuntu ([тыц](https://github.com/mrDoctorWho/vk4xmpp/blob/master/library/vkapi.py#L143)). Я не знаю, что там делает ВК с User-Agent при обработке запросов API, но вряд ли это бы как-то влияло.

А разница User-Agent'ов точно никак не должна влиять, да и не влияет, потому что транспорт запрашивает с Firefox в качестве User-Agent, а мы открываем, например, в Chromium.

**Comment by mrDoctorWho** [comment]
0b6de3bcadc6849ec378414efedfd1af4960ae45
