### ISSUE TITLE
Captcha forms

### ISSUE THREAD

**Issue by yagiza** [mrDoctorWho/vk4xmpp#69]
Почему-то капчи от вКонтакта приходят не в виде формочек, а в виде сообщений со ссылкой. Это ужасно.
Что, XEP-0158 не реализован? Почему?

**Comment by yagiza** [comment]
Несколько месяцев ждал, пока какой-нибудь транспорт пришлёт мне капчу, чтобы выяснить, в чём дело. Почему капча не появляется, не смотря на то, что заявлена поддержка.

Как оказалось, проблема опять в несоблюдении протокола.

Согласно [XEP-0158, пункт 3.1.2](http://xmpp.org/extensions/xep-0158.html#protocol-challenge), форма с капчей ДОЛЖНА содержать скрытое поле "challenge", содержащее challenge ID (подпункт 7).
Присылаемая транспортом форма этого поля не содержит. Соответственно, клиент, корректно проверяющие форму капчи на валидность, игнорируют её и капчу не отображают.

Пожалуйста, снимите флажок "invalid" и пофиксите багу.

**Comment by mrDoctorWho** [comment]
@yagiza, challenge ID не представляет никакой значимости. Если клиенты игнорируют всё без ID, они сами виноваты. Tkabber поддерживает капчу, присылаемую транспортом.

**Comment by yagiza** [comment]
Всё ещё не работает.
Challenge ID олжно совпадать с ID сообщения!
