### ISSUE TITLE
Уведомлять о фотографиях (аватарках)

### ISSUE THREAD

**Issue by ghost** [mrDoctorWho/vk4xmpp#70]
Большинство современных клиентов достаточно умны, чтобы не грузить аватарку автоматом, если предварительно не получили уведомление о наличии/обновлении оной.
Считаю, что необходимо реализовать хотя бы XEP-0153: vCard-Based Avatars для этого (т. е. слать элемент <x xmlns='vcard-temp:x:update'>, содержащий хеш аватарки, в presence'ах от транспорта.
В идеале было бы неплохо реализовать и XEP-0084: User Avatar (передавать уведомления и аватарки, имитируя PEP), но это уже верх крутизны.

**Comment by yagiza** [comment]
1. Добавление пустого элемента <x xmlns='vcard-temp:x­:update'/> в презенс не увеличит количество строф или запросов от пользователей. Зато XEP-0153 не будет нарушаться.
2. Смена аватарки - редкое явление. Так что, вряд ли уведомление об этом событии увеличит нагрузку сервера.
3. Однажды скачав аватарку клиент кеширует её, и больше не будет скачивать, если будут приходить презенсы с тем же хешем.
4. Единственный случай, когда может возрасти нагрузка на канал - это когда клиент впервые подключился к транспорту и в его кеше пока нет аватрок его контаков вКонтакте. В этом случае действительно, если транспорт начнёт сигналить ему об аватарках контактов, он кинется их выкачивать. Однако, тут проблему можно решить очень просто: добавить транспорту настройку, ограничивающую отправку презенсов с аватарками по времени. Например, не чаще, чем раз в секунду. Или раз в 10 секунд. Или раз в минуту.
В этом случае, после подключения к транспорту, он сначала пришлёт ото всех контактов презенсы с пустым элементом <x xmlns='vcard-temp:x­:update'/>, а затем, скачав аватарки, начнёт рассылать презенсы с хешем, но не чаще, чем указано в настройке.
Такое решение по крайней мере, более логично, чем привязывать отправку хеша к смене статуса контакта, и кроме того, позволит контролировать загруженность канала.

**Comment by mrDoctorWho** [comment]
Я не вижу ни малейшего смысла в отправке пустого элемента <x>. Это никому не поможет, а транспорту только навредит. Транспорт отправляет <x> для *новых* контактов, которых не было в сети. Клиент о них ничего не знает до их появления онлайн, Добавление таймера не просто ненужная или глупая затея, она добавит сложности. А согласно философии Python, «Simple is better than complex.»

**Comment by yagiza** [comment]
Я реально не понимаю, как транспорту может навредить добавление пустого элемента в строфу?
Основная проблема, что если в момент подключения транспорт уже **был**  в сети, то транспорт так и не пришлёт хеш аватарки, до тех пор, пока пользователю не придёт в голову выйти в оффлайн, а затем снова выйти в онлайн. Когда это произойдёт - никому не известно. Таком образом, существующая реализация не только нарушает XEP, но и приводит, к тому, что для некоторых контактов хеш аватарки так никогда и не придёт, и аватарка не отобразится. Это плохо.

**Comment by mrDoctorWho** [comment]
Наряду с увеличением объёма единицы отправленной станзы и объёма отправленного за единицу времени (привет ejabberd), это добавит нагрузку на транспорт: клиент вполне вероятно начнёт запрашивать аватарки (что критично) или посчитает, что у пользователя больше нет аватарки и удалит файл, а когда хеш появится, он запросит аватарку снова. Нужно заметить, что я не единственный, кто порой игнорирует стандарты. Транспорт совместим с наиболее популярными клиентами, даже с qip. Но всем не угодишь.

А ещё в транспорте уже есть глобальный ограничитель отправки станз по премени (объём и тип не учитывается), писать новый я не стану. По крайней мере, для vk4xmpp, потому что я закрыл проект и только исправляю ошибки, а это максимум небольшая недоработка, притом сомнительная: я сознательно пошёл на такое решение, после того как отказался от идеи хранить хеши в базе. В итоге пользователям присылается (когда присылается) всегда свежий хеш.

**Comment by yagiza** [comment]
На самом деле, именно **отсутствие** пустого элемента в презенсе приведёт к принудительному скачиванию визиток со стороны клиента. Поскольку отсутствие данного элемента сообщает клиенту, что XEP-0153 не поддерживается и ждать хеша не стоит. Если клиент поддерживает принудительное получение аватарок, то он будет их скачивать *только* для контактов, от которых пришёл презенс, не содержащий элемента <x xmlns='vcard-temp:x:update'/>. Т. е. потенциально именно его отсутствие нагружает транспорт лишними скачиваниями визиток со стороны клиентов.
Также, согласно XEP, если у контакта нет аватарки, об этом сообщается с помощью элемента <x xmlns='vcard-temp:x:update'/>, содержащего пустой элемент <photo/>. Если кто-то и написал клиент настолько кривой, что тот воспринимает пустой элемент <x xmlns='vcard-temp:x:update'/>, как сигнал о том, что аватарки нет, то я не думаю, что имеет смысл обращать на него внимание. Если автор **настолько** криворук, то я думаю в его клиенте всё остальное тоже глючит, и вряд ли кто-то таким клиентом станет пользоваться.
