### ISSUE TITLE
Групповые чаты.

### ISSUE THREAD

**Issue by raider444** [mrDoctorWho/vk4xmpp#79]
Здравствуйте, VK4XMPP Transport #246-b537c3c / CPython 2.7.3
Перестали работать. Приходит приглашение, захожу в конфу, там нет ни пользователей ничего. Сообщения в сторону конференции вроде бы как уходят, а до вк доходить перестали. Из вктоже не проходят. В логах ничего по этому поводу не увидел. Клиент psi+ 0.16.261/win8[x64], так же imessages (osx 10.10)

**Comment by mrDoctorWho** [comment]
Здравствуйте. Включена ли опция «Show all chat users» в конфиге пользователя?

**Comment by raider444** [comment]
Опция включена.
