### ISSUE TITLE
Перестала работать регистрация после обновления

### ISSUE THREAD

**Issue by raider444** [mrDoctorWho/vk4xmpp#90]
Название:	VK4XMPP Transport
Версия:	#284-8191314
ОС:	Linux 3.3.2psykernel [x86_64] / CPython 2.7.3

У двух учёток перестали быть валидными токены (на остальных не проверялось)
При попытке повторной регистрации ни по паролю, ни по токену зарегистрироваться не получается. Пробовал заново авторизовать приложение ВК, не помогло. Телефон указан верно (формат: +7хххххххххх), пароль тоже, так же пробовал использовать e-mail, что так же не дало положительных результатов.
Лог:
25.04.2015 20:22:10 DEBUG:vk4xmpp: Send registration form to user (jid: vk_raider@psynet.su)
25.04.2015 20:22:23 DEBUG:vk4xmpp: user want to use a password (jid: vk_raider@psynet.su)
25.04.2015 20:22:23 DEBUG:vk4xmpp: User initialized (jid: vk_raider@psynet.su)
25.04.2015 20:22:23 DEBUG:vk4xmpp: User connecting (jid: vk_raider@psynet.su)
25.04.2015 20:22:24 DEBUG:vk4xmpp: VK initialized (jid: vk_raider@psynet.su)
25.04.2015 20:22:24 DEBUG:vk4xmpp: VK going to authenticate (jid: vk_raider@psynet.su)
25.04.2015 20:23:03 DEBUG:vk4xmpp: Send registration form to user (jid: vk_raider@psynet.su)
25.04.2015 20:23:13 DEBUG:vk4xmpp: user won't use a password (jid: vk_raider@psynet.su)
25.04.2015 20:23:13 DEBUG:vk4xmpp: User initialized (jid: vk_raider@psynet.su)
25.04.2015 20:23:13 DEBUG:vk4xmpp: User connecting (jid: vk_raider@psynet.su)
25.04.2015 20:23:13 DEBUG:vk4xmpp: VK initialized (jid: vk_raider@psynet.su)
25.04.2015 20:23:13 DEBUG:vk4xmpp: VK going to authenticate (jid: vk_raider@psynet.su)

crash/VK.auth.txt
| 25.04.2015 (19:44:41) |
Traceback (most recent call last):
  File "/opt/vk4xmpp/gateway.py", line 266, in auth
    self.checkData()
  File "/opt/vk4xmpp/gateway.py", line 234, in checkData
    raise api.VkApiError("Incorrect phone or password")
VkApiError: Incorrect phone or password

crash/initializeUser.txt
| 25.04.2015 (19:44:41) |
Traceback (most recent call last):
  File "library/utils.py", line 25, in execute
    result = handler(*list)
  File "modules/mod_iq_register.py", line 15, in initializeUser
    connect = user.connect(True)
  File "/opt/vk4xmpp/gateway.py", line 544, in connect
    self.auth = self.vk.auth(self.token, raise_exc=raise_exc)
  File "/opt/vk4xmpp/gateway.py", line 266, in auth
    self.checkData()
  File "/opt/vk4xmpp/gateway.py", line 234, in checkData
    raise api.VkApiError("Incorrect phone or password")
VkApiError: Incorrect phone or password

**Comment by mrDoctorWho** [comment]
В приведённых ошибках приутствует код, которого нет в ревизии 284. Обновите vk4xmpp и попробуйте снова.

**Comment by raider444** [comment]
Попробовал удалить полностью всё что есть в директории, включая .git*, сделал git clone снуля, перенёс конфиг и базу, 
в vk4xmpp.log
25.04.2015 20:49:04 DEBUG:vk4xmpp: Send registration form to user (jid: vk_raider@psynet.su)
25.04.2015 20:49:14 DEBUG:vk4xmpp: user won't use a password (jid: vk_raider@psynet.su)
25.04.2015 20:49:14 DEBUG:vk4xmpp: User initialized (jid: vk_raider@psynet.su)
25.04.2015 20:49:14 DEBUG:vk4xmpp: User connecting (jid: vk_raider@psynet.su)
25.04.2015 20:49:16 DEBUG:vk4xmpp: VK initialized (jid: vk_raider@psynet.su)
25.04.2015 20:49:16 DEBUG:vk4xmpp: VK going to authenticate (jid: vk_raider@psynet.su)

в crash вообще ничего не пишется
Права верны.

**Comment by mrDoctorWho** [comment]
Что в последнем случае отвечает транспорт пользователю при регистрации?

**Comment by raider444** [comment]
Если по токену (точнее по ссылке с токеном)
Ошибка отправки регистрационных данных.
Причина: Not authorized.
The sender must provide proper credentials before being allowed to perform the action, or has provided improper credentials.
The token is invalid (jid: vk_raider@psynet.su) Try logging in by token.

**Comment by mrDoctorWho** [comment]
Теперь должно работать. Если проблема повторяется — открывайте это issue снова.

Могут возникнуть проблемы с прохождением капчи, Если вы **уверены**, что описанные [здесь](https://jabberon.ru/articles/2014/12/12/%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82-%D0%B2%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%B5-faq/#q15) инструкции оне помогают, открывайте issue по капче.
